# Generated by Django 3.0.11 on 2021-01-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('email', models.TextField()),
                ('first_name', models.TextField(blank=True, default='', max_length=50)),
                ('last_name', models.TextField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
